apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: photoatom-keycloak-auth
  labels:
    app: kc
spec:
  instances: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  db:
    vendor: postgres
    usernameSecret:
      name: photoatom-postgres-keycloak-creds
      key: username
    passwordSecret:
      name: photoatom-postgres-keycloak-creds
      key: password
    host: postgres-rw.photoatom-postgres-database.svc
    database: keycloak
    port: 5432
    poolInitialSize: 1
    poolMinSize: 2
    poolMaxSize: 3
  http:
    tlsSecret: photoatom-keycloak-cert
  hostname:
    hostname: auth.photoatom.local
  unsupported:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
        containers:
          - env:
              - name: KEYCLOAK_DB_USER
                valueFrom:
                  secretKeyRef:
                    name: photoatom-postgres-keycloak-creds
                    key: username
              - name: KEYCLOAK_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: photoatom-postgres-keycloak-creds
                    key: password
  ingress:
    enabled: false
